version: '3'
services:
  app:
    build: ./
    container_name: app
    ports:
      - 8080:80
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: none
